PANDAS PRACTICE

Pandas Tutorial

Pandas is an open-source, BSD-licensed Python library that provides high-performance, easy-to-use data structures and powerful data analysis tools.

Agenda
1. What is a DataFrame?
2. What is a Series?
3. Different Operations in Pandas

In [24]:
import pandas as pd
import numpy as np

In [25]:
# Playing with Dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns= ['Col1', 'Col2', 'Col3', 'Col4'])

In [26]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [27]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [28]:
df.head

<bound method NDFrame.head of       Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19>

In [29]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [30]:
df.to_csv('try.csv')

In [31]:
#Accessing the elements

#1. loc (row index mainly)
#2. iloc (both row and column index)

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [32]:
type(df.loc['Row1'])

pandas.core.series.Series

In [33]:
df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [34]:
df.iloc[0:3,1:3]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10

In [35]:
type(df.iloc[0:3,1:3])

pandas.core.frame.DataFrame

In [36]:
#convert Dataframes into an array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [37]:
df.iloc[:,1:].values.shape

(5, 3)

In [38]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [39]:
df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

In [40]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [41]:
df['Col3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Col3, dtype: int32

In [42]:
df[['Col2', 'Col3']]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10
Row4    13    14
Row5    17    18

In [43]:
df.describe()

            Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 292.0+ bytes

In [45]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [46]:
df = pd.read_csv('mercedesbenz.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'mercedesbenz.csv'

In [ ]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Get unique category counts\
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [ ]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

CSV

In [ ]:
from io import StringIO, BytesIO

In [ ]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [ ]:
type(data)

str

In [ ]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
df = pd.read_csv(StringIO(data),usecols=['col1', 'col2'])

In [ ]:
df

  col1 col2
0    x    y
1    a    b
2    c    d

In [ ]:
df.to_csv('Test.csv')

In [ ]:
#Specifying columns data types

data = ('a,b,c,d \n'
        '1,2,3,4 \n'
        '5,6,7,8\n'
        '9,10,11')

In [ ]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [ ]:
df = pd.read_csv(StringIO(data),dtype=float)

In [ ]:
df

     a     b     c   d
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.0  8.0
2  9.0  10.0  11.0  NaN

In [ ]:
df['a'][1]

5.0

In [ ]:
df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8588\566591662.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

In [ ]:
df

   a   b     c   d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [ ]:
df.dtypes

a       Int64
b       int32
c     float64
d     float64
dtype: object

In [ ]:
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [ ]:
pd.read_csv(StringIO(data),index_col = 0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [ ]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,\n')

In [ ]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [ ]:
df = pd.read_csv(StringIO(data),index_col=False)

In [ ]:
df = pd.read_csv(StringIO(data),usecols=['b', 'c'],index_col=False)

In [ ]:
df

        b    c
0   apple  bat
1  orange  cow

In [ ]:
#Quoting and Escape Characters. Very useful in NLP

data = 'a, b,\n "hello, \\Bob\\", nice to see you",5'

In [ ]:
df = pd.read_csv(StringIO(data),escapechar='\\')

In [ ]:
df

             a                  b  Unnamed: 2
 "hello   Bob"   nice to see you"           5

In [ ]:
#URL TO CSV

# df = pd.read_csv(
#     'https://download.bls.gov/pub/time.series/cu/cu.item',
#     sep='\t'
# )

READ JSON TO CSV

In [ ]:
import pandas as pd
import json

Data = [
    {"Name": "Alice", "Age": 25, "City": "Kathmandu"},
    {"Name": "Bob", "Age": 30, "City": "Pokhara"},
    {"Name": "Charlie", "Age": 28, "City": "Lalitpur"}
]



json_str = json.dumps(Data)   # Convert list of dicts to JSON string
df = pd.read_json(json_str)
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur

In [ ]:
df.to_json(orient="records")

'[{"Name":"Alice","Age":25,"City":"Kathmandu"},{"Name":"Bob","Age":30,"City":"Pokhara"},{"Name":"Charlie","Age":28,"City":"Lalitpur"}]'

In [ ]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df = pd.read_csv(url, header=None)

# Display the first 5 rows neatly
print(df.head().to_string())

   0      1     2     3     4    5     6     7     8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   735

READING HTML CONTENTS

In [ ]:
url = "https://www.fdic.gov/bank/individual/failed/banklist.html"

dfs = pd.read_html(url)

In [ ]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

READING EXCEL FILES

In [ ]:
df_excel = pd.read_excel('excel.xlsx')

In [ ]:
df_excel.head()

   0  1   2   3
0  4  5   6   7
1  8  9  10  11

PICKLING

In [ ]:
df_excel.to_pickle('df_excel')

In [ ]:
df = pd.read_pickle('df_excel')

In [ ]:
df.head()

   0  1   2   3
0  4  5   6   7
1  8  9  10  11