PANDAS PRACTICE

Pandas Tutorial

Pandas is an open-source, BSD-licensed Python library that provides high-performance, easy-to-use data structures and powerful data analysis tools.

Agenda
1. What is a DataFrame?
2. What is a Series?
3. Different Operations in Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Playing with Dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns= ['Col1', 'Col2', 'Col3', 'Col4'])

In [3]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [4]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [5]:
df.head

<bound method NDFrame.head of       Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19>

In [6]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [7]:
df.to_csv('try.csv')

In [8]:
#Accessing the elements

#1. loc (row index mainly)
#2. iloc (both row and column index)

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [9]:
type(df.loc['Row1'])

pandas.core.series.Series

In [10]:
df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [11]:
df.iloc[0:3,1:3]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10

In [12]:
type(df.iloc[0:3,1:3])

pandas.core.frame.DataFrame

In [13]:
#convert Dataframes into an array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [14]:
df.iloc[:,1:].values.shape

(5, 3)

In [15]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [16]:
df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

In [17]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [18]:
df['Col3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Col3, dtype: int32

In [19]:
df[['Col2', 'Col3']]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10
Row4    13    14
Row5    17    18

In [20]:
df.describe()

            Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 292.0+ bytes

In [22]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [23]:
df = pd.read_csv('mercedesbenzyes.csv')

In [24]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# Get unique category counts\
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [26]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

CSV

In [27]:
from io import StringIO, BytesIO

In [28]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [29]:
type(data)

str

In [30]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [31]:
df = pd.read_csv(StringIO(data),usecols=['col1', 'col2'])

In [32]:
df

  col1 col2
0    x    y
1    a    b
2    c    d

In [33]:
df.to_csv('Test.csv')

In [34]:
#Specifying columns data types

data = ('a,b,c,d \n'
        '1,2,3,4 \n'
        '5,6,7,8\n'
        '9,10,11')

In [35]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [36]:
df = pd.read_csv(StringIO(data),dtype=float)

In [37]:
df

     a     b     c   d
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.0  8.0
2  9.0  10.0  11.0  NaN

In [38]:
df['a'][1]

5.0

In [39]:
df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_24088\566591662.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

In [40]:
df

   a   b     c   d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [41]:
df.dtypes

a       Int64
b       int32
c     float64
d     float64
dtype: object

In [42]:
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [43]:
pd.read_csv(StringIO(data),index_col = 0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [44]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,\n')

In [45]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [46]:
df = pd.read_csv(StringIO(data),index_col=False)

In [47]:
df = pd.read_csv(StringIO(data),usecols=['b', 'c'],index_col=False)

In [48]:
df

        b    c
0   apple  bat
1  orange  cow

In [49]:
#Quoting and Escape Characters. Very useful in NLP

data = 'a, b,\n "hello, \\Bob\\", nice to see you",5'

In [50]:
df = pd.read_csv(StringIO(data),escapechar='\\')

In [51]:
df

             a                  b  Unnamed: 2
 "hello   Bob"   nice to see you"           5

In [52]:
#URL TO CSV

# df = pd.read_csv(
#     'https://download.bls.gov/pub/time.series/cu/cu.item',
#     sep='\t'
# )

READ JSON TO CSV

In [53]:
import pandas as pd
import json

Data = [
    {"Name": "Alice", "Age": 25, "City": "Kathmandu"},
    {"Name": "Bob", "Age": 30, "City": "Pokhara"},
    {"Name": "Charlie", "Age": 28, "City": "Lalitpur"}
]



json_str = json.dumps(Data)   # Convert list of dicts to JSON string
df = pd.read_json(json_str)
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur

In [54]:
df.to_json(orient="records")

'[{"Name":"Alice","Age":25,"City":"Kathmandu"},{"Name":"Bob","Age":30,"City":"Pokhara"},{"Name":"Charlie","Age":28,"City":"Lalitpur"}]'

In [ ]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df = pd.read_csv(url, encoding="latin1", header=None)

# Display the first 5 rows neatly
print(df.head().to_string())

READING HTML CONTENTS

In [ ]:
url = "https://www.fdic.gov/bank/individual/failed/banklist.html"

df = pd.read_html(url)

ImportError: lxml not found, please install it