PANDAS PRACTICE

Pandas Tutorial

Pandas is an open-source, BSD-licensed Python library that provides high-performance, easy-to-use data structures and powerful data analysis tools.

Agenda
1. What is a DataFrame?
2. What is a Series?
3. Different Operations in Pandas

In [21]:
import pandas as pd
import numpy as np

In [22]:
# Playing with Dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns= ['Col1', 'Col2', 'Col3', 'Col4'])

In [23]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [24]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [25]:
df.head

<bound method NDFrame.head of       Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19>

In [26]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [27]:
df.to_csv('try.csv')

In [28]:
#Accessing the elements

#1. loc (row index mainly)
#2. iloc (both row and column index)

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [29]:
type(df.loc['Row1'])

pandas.core.series.Series

In [30]:
df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [31]:
df.iloc[0:3,1:3]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10

In [33]:
type(df.iloc[0:3,1:3])

pandas.core.frame.DataFrame

In [34]:
#convert Dataframes into an array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [35]:
df.iloc[:,1:].values.shape

(5, 3)

In [36]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64